name: Deploy Next.js to Azure App Service

on:
  push:
    branches: [ main ]
    paths:
      - 'frontend/**'
      - '.github/workflows/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: ls -la frontend  # デバッグ用（最初だけ便利）

      # ZIP Deploy: frontendフォルダだけ送る → サーバ側(Oryx)で npm i / next build 実行
      - name: Deploy to Azure Web App (ZIP/OneDeploy)
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'app-002-gen10-step3-2-node-oshima13'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_190E84D8AB6C493BAA95A424A51EFF6C }}
          package: .
