name: Deploy Next.js to App Service
on:
  push:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: ./package-lock.json   # ← 修正

      - run: npm ci
      - run: npm run build

      # スタンドアロン成果物を zip 化
      - name: Prepare artifact
        run: |
          mkdir -p out_zip
          # .next/standalone 直下には server.js と node_modules が揃っています
          cp -r .next/standalone/* out_zip/
          mkdir -p out_zip/.next
          cp -r .next/static out_zip/.next/
          cp -r public out_zip/public || true

          # 起動コマンドを next ではなく node server.js に固定
          cat > out_zip/package.json << 'JSON'
          {
            "name": "app",
            "version": "1.0.0",
            "private": true,
            "scripts": {
              "start": "node server.js"
            }
          }
          JSON

      - name: Zip artifact
        run: (cd out_zip && zip -r ../app.zip .)

      # 409 回避のためリトライ付きで配布
      - name: Deploy artifact
        uses: Wandalen/wretry.action@v1.3.0
        with:
          attempt_limit: 5
          attempt_delay: 25000
          action: azure/webapps-deploy@v3
          with: |
            app-name: app-002-gen10-step3-2-node-oshima13
            publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_190E84D8AB6C493BAA95A424A51EFF6C }}
            package: app.zip   # ← 修正
